version: '3'

services:
  backend:
    image: backend-python
    build:
      context: ./backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    ports:                                #Do usunięcia po debugowaniu
      - "${BACKEND_PORT}:${BACKEND_PORT}" #Do usunięcia po debugowaniu
    env_file:
      - .env
    
  frontend:
    image: frontend-react
    build:
      context: ./frontend
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "${EXPOSED_FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    depends_on:
      - backend
